stages:
  - mirroring
  - routines
  - pre_build
  - build
  - publish

include: '/dist/gitlab-release.yml'

pages:
  stage: routines
  tags:
    - docker
  image: registry.gitlab.com/manticoresearch/dev/manticoredocs:latest
  script:
    - cd docs
    - make html
    - cd -
    - mkdir .public
    - cp -r docs/build/html/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

job_mirror:
  stage: mirroring
  tags:
    - dev-host
  only:
    - master
  script:
    - ~/gitsync.sh

simple_tests:
  stage: routines
  except:
    variables:
      - $WHAT
  tags:
    - specdocker
  dependencies: []
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  variables:
    CTEST_BUILD_CONFIGURATION: "Debug"
  script:
    - ctest -V -S /work/gltest.cmake
  artifacts:
    paths:
    - build/here
    - build/test/test_*/report.txt
    - build/test/error*.txt
    - build/test/searchd.log
    - build/junit_*.xml
    expire_in: 12 hrs
    when: always
  retry: 1

release_tests:
  stage: routines
  except:
    variables:
      - $WHAT
  tags:
    - specdocker
  dependencies: []
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  variables:
    CTEST_BUILD_CONFIGURATION: "RelWithDebInfo"
  script:
    - ctest -V -S /work/gltest.cmake
  artifacts:
    paths:
    - build/here
    - build/test/test_*/report.txt
    - build/test/error*.txt
    - build/test/searchd.log
    - build/junit_*.xml
    expire_in: 12 hrs
    when: always
  retry: 1

push_results:
  stage: publish
  except:
    variables:
      - $WHAT
  tags:
    - specdocker
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  dependencies:
    - simple_tests
    - release_tests
  variables:
    GIT_STRATEGY: none
  script:
    - ctest -S /work/upload.cmake
  when: always
  artifacts:
    paths:
    - results.html
    reports:
      junit: build/junit_*.xml
  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: http://$CDASH_URL/CDash/public/index.php?project=Manticoresearch&filtercount=1&field1=revision&compare1=63&value1=$CI_COMMIT_SHA
  retry: 1
  allow_failure: true
